[project]
name = "eiatestcatalogue"
version = "0.1.0"
description = "A Python environment used to test EIA Test Catalogue content"
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "rdflib>=7.1.4",
    "httpx>=0.28.1,<0.29.0",
    "kurra>=1.5.2",
]


