# resolves eurovoc IRIs directly to get RDF/XML which is parsed to get the prefLabel in English
from rdflib import Graph, URIRef, SDO, SKOS

concepts = [
    "http://eurovoc.europa.eu/4930" ,
    "http://eurovoc.europa.eu/2902" ,
    "http://eurovoc.europa.eu/5050" ,
    "http://eurovoc.europa.eu/1221" ,
    "http://eurovoc.europa.eu/3122" ,
    "http://eurovoc.europa.eu/2435" ,
    "http://eurovoc.europa.eu/4940" ,
    "http://eurovoc.europa.eu/4165" ,
    "http://eurovoc.europa.eu/5971" ,
    "http://eurovoc.europa.eu/5988" ,
    "http://eurovoc.europa.eu/5482" ,
    "http://eurovoc.europa.eu/6384" ,
    "http://eurovoc.europa.eu/75" ,
    "http://eurovoc.europa.eu/316" ,
    "http://eurovoc.europa.eu/3157" ,
    "http://eurovoc.europa.eu/416" ,
    "http://eurovoc.europa.eu/510" ,
    "http://eurovoc.europa.eu/632" ,
    "http://eurovoc.europa.eu/3158" ,
    "http://eurovoc.europa.eu/1042" ,
    "http://eurovoc.europa.eu/602" ,
    "http://eurovoc.europa.eu/5651" ,
    "http://eurovoc.europa.eu/6390" ,
    "http://eurovoc.europa.eu/1204" ,
    "http://eurovoc.europa.eu/609" ,
    "http://eurovoc.europa.eu/1245" ,
    "http://eurovoc.europa.eu/1278" ,
    "http://eurovoc.europa.eu/1169" ,
    "http://eurovoc.europa.eu/981" ,
    "http://eurovoc.europa.eu/2680" ,
    "http://eurovoc.europa.eu/4630" ,
    "http://eurovoc.europa.eu/2428" ,
    "http://eurovoc.europa.eu/1736" ,
    "http://eurovoc.europa.eu/1779" ,
    "http://eurovoc.europa.eu/1892" ,
    "http://eurovoc.europa.eu/1991" ,
    "http://eurovoc.europa.eu/2056" ,
    "http://eurovoc.europa.eu/4545" ,
    "http://eurovoc.europa.eu/3834" ,
    "http://eurovoc.europa.eu/2214" ,
    "http://eurovoc.europa.eu/2215" ,
    "http://eurovoc.europa.eu/3760" ,
    "http://eurovoc.europa.eu/2372" ,
    "http://eurovoc.europa.eu/2524" ,
    "http://eurovoc.europa.eu/3318" ,
    "http://eurovoc.europa.eu/2568" ,
    "http://eurovoc.europa.eu/2707" ,
    "http://eurovoc.europa.eu/2724" ,
    "http://eurovoc.europa.eu/2943" ,
    "http://eurovoc.europa.eu/4426" ,
    "http://eurovoc.europa.eu/3967" ,
    "http://eurovoc.europa.eu/4352" ,
    "http://eurovoc.europa.eu/6267" ,
    "http://eurovoc.europa.eu/5288" ,
    "http://eurovoc.europa.eu/6386" ,
    "http://eurovoc.europa.eu/597" ,
    "http://eurovoc.europa.eu/5463" ,
    "http://eurovoc.europa.eu/4783" ,
    "http://eurovoc.europa.eu/1151" ,
    "http://eurovoc.europa.eu/1148" ,
    "http://eurovoc.europa.eu/4921" ,
    "http://eurovoc.europa.eu/4930" ,
    "http://eurovoc.europa.eu/385" ,
    "http://eurovoc.europa.eu/2114" ,
    "http://eurovoc.europa.eu/3836" ,
    "http://eurovoc.europa.eu/2395" ,
    "http://eurovoc.europa.eu/5304" ,
    "http://eurovoc.europa.eu/5261" ,
    "http://eurovoc.europa.eu/5346" ,
    "http://eurovoc.europa.eu/2907" ,
    "http://eurovoc.europa.eu/5244" ,
    "http://eurovoc.europa.eu/5966" ,
    "http://eurovoc.europa.eu/3157" ,
    "http://eurovoc.europa.eu/2907" ,
    "http://eurovoc.europa.eu/4165" ,
    "http://eurovoc.europa.eu/5346" ,
    "http://eurovoc.europa.eu/3834" ,
    "http://eurovoc.europa.eu/3836" ,
    "http://eurovoc.europa.eu/5304" ,
    "http://eurovoc.europa.eu/5261" ,
    "http://eurovoc.europa.eu/5971" ,
    "http://eurovoc.europa.eu/5988" ,
    "http://eurovoc.europa.eu/316" ,
    "http://eurovoc.europa.eu/1042" ,
    "http://eurovoc.europa.eu/981" ,
    "http://eurovoc.europa.eu/1736" ,
    "http://eurovoc.europa.eu/1779" ,
    "http://eurovoc.europa.eu/2056" ,
    "http://eurovoc.europa.eu/4545" ,
    "http://eurovoc.europa.eu/2215" ,
    "http://eurovoc.europa.eu/3760" ,
    "http://eurovoc.europa.eu/2568" ,
    "http://eurovoc.europa.eu/5288" ,
    "http://eurovoc.europa.eu/4783" ,
    "http://eurovoc.europa.eu/1991" ,
    "http://eurovoc.europa.eu/2707" ,
    "http://eurovoc.europa.eu/2943" ,
    "http://eurovoc.europa.eu/75" ,
    "http://eurovoc.europa.eu/416" ,
    "http://eurovoc.europa.eu/3158" ,
    "http://eurovoc.europa.eu/510" ,
    "http://eurovoc.europa.eu/6267" ,
    "http://eurovoc.europa.eu/2724" ,
    "http://eurovoc.europa.eu/4352" ,
    "http://eurovoc.europa.eu/3318" ,
    "http://eurovoc.europa.eu/6390" ,
    "http://eurovoc.europa.eu/2114" ,
    "http://eurovoc.europa.eu/4426" ,
    "http://eurovoc.europa.eu/5244" ,
    "http://eurovoc.europa.eu/4940" ,
    "http://eurovoc.europa.eu/4630" ,
    "http://eurovoc.europa.eu/3122" ,
    "http://eurovoc.europa.eu/2435" ,
    "http://eurovoc.europa.eu/2395" ,
    "http://eurovoc.europa.eu/2214" ,
    "http://eurovoc.europa.eu/2372" ,
    "http://eurovoc.europa.eu/1169" ,
    "http://eurovoc.europa.eu/6386" ,
    "http://eurovoc.europa.eu/385" ,
    "http://eurovoc.europa.eu/2428" ,
    "http://eurovoc.europa.eu/1151" ,
    "http://eurovoc.europa.eu/1892" ,
    "http://eurovoc.europa.eu/2680" ,
    "http://eurovoc.europa.eu/1148" ,
    "http://eurovoc.europa.eu/1245" ,
    "http://eurovoc.europa.eu/1278" ,
    "http://eurovoc.europa.eu/6384" ,
    "http://eurovoc.europa.eu/5482" ,
    "http://eurovoc.europa.eu/602" ,
    "http://eurovoc.europa.eu/1204" ,
    "http://eurovoc.europa.eu/5463" ,
    "http://eurovoc.europa.eu/2524" ,
    "http://eurovoc.europa.eu/5966" ,
    "http://eurovoc.europa.eu/597" ,
    "http://eurovoc.europa.eu/4921" ,
    "http://eurovoc.europa.eu/5651" ,
    "http://eurovoc.europa.eu/632" ,
]

g2 = Graph()

for concept in concepts:
    g = Graph().parse(concept, format="xml")
    iri = URIRef(concept)
    q = f"""
        PREFIX schema: <{SDO}>
        PREFIX skos: <{SKOS}>
        
        CONSTRUCT {{
            <{concept}> schema:name $lbl .
        }}
        WHERE {{
            <{concept}> skos:prefLabel ?lbl .
            
            FILTER (LANG(?lbl) = 'en')
        }}
        """

    g2 += g.query(q)
    print(iri)
    print(len(g2))

g2.serialize(destination="eurovoc.ttl", format="longturtle")

