data = open("../../resources/vocabularies/envthes.ttl").read()

replacements = {
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abampere": "http://qudt.org/vocab/unit/A_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abcoulomb": "http://qudt.org/vocab/unit/C_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abfarad": "http://qudt.org/vocab/unit/FARAD_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abhenry": "http://qudt.org/vocab/unit/H_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abohm": "http://qudt.org/vocab/unit/OHM_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Absiemen": "http://qudt.org/vocab/unit/S_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abtesla": "http://qudt.org/vocab/unit/T_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Abvolt": "http://qudt.org/vocab/unit/V_Ab" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#AbvoltSecond": "http://qudt.org/vocab/unit/V_Ab-SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#AmpereTurn": "http://qudt.org/vocab/unit/AT" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Dyne": "http://qudt.org/vocab/unit/DYN" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Erg": "http://qudt.org/vocab/unit/ERG" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Ergsecond": "http://qudt.org/vocab/unit/ERG-SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Gauss": "http://qudt.org/vocab/unit/GAUSS" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Gilbert": "http://qudt.org/vocab/unit/GI" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Gram": "http://qudt.org/vocab/unit/GM" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#KilogramKelvin": "http://qudt.org/vocab/unit/KiloGM-K" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Maxwell": "http://qudt.org/vocab/unit/MX" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#MoleKelvin": "http://qudt.org/vocab/unit/MOL-K" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Oersted": "http://qudt.org/vocab/unit/OERSTED" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Poise": "http://qudt.org/vocab/unit/POISE" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Statampere": "http://qudt.org/vocab/unit/A_Stat" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Statcoulomb": "http://qudt.org/vocab/unit/C_Stat" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Statfarad": "http://qudt.org/vocab/unit/FARAD_Stat" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Stathenry": "http://qudt.org/vocab/unit/H_Stat" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Statohm": "http://qudt.org/vocab/unit/OHM_Stat" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Statvolt": "http://qudt.org/vocab/unit/V_Stat" ,
    
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Ampere": "http//qudt.org/vocab/unit/A" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Becquerel": "http//qudt.org/vocab/unit/BQ" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Candela": "http//qudt.org/vocab/unit/CD" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Coulomb": "http//qudt.org/vocab/unit/C" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Farad": "http//qudt.org/vocab/unit/FARAD" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Gray": "http//qudt.org/vocab/unit/GRAY" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Henry": "http//qudt.org/vocab/unit/H" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Hertz": "http//qudt.org/vocab/unit/HZ" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Joule": "http//qudt.org/vocab/unit/J" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#JoulePerKelvin": "http//qudt.org/vocab/unit/J-PER-K" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#JoulePerMole": "http//qudt.org/vocab/unit/J-PER-MOL" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#JoulePerTesla": "http//qudt.org/vocab/unit/J-PER-T" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#JouleSecond": "http//qudt.org/vocab/unit/J-SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Katal": "http//qudt.org/vocab/unit/KAT" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Kelvin": "http//qudt.org/vocab/unit/K" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#KelvinPerWatt": "http//qudt.org/vocab/unit/K-PER-W" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Kilogram": "http//qudt.org/vocab/unit/KiloGM" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Lumen": "http//qudt.org/vocab/unit/LM" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Lux": "http//qudt.org/vocab/unit/LUX" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Mole": "http//qudt.org/vocab/unit/MOL" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Newton": "http//qudt.org/vocab/unit/N" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Ohm": "http//qudt.org/vocab/unit/OHM" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Pascal": "http//qudt.org/vocab/unit/PA" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#PascalSecond": "http//qudt.org/vocab/unit/PA-SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Radian": "http//qudt.org/vocab/unit/RAD" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#RadianPerSecond": "http//qudt.org/vocab/unit/RAD-PER-SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Second": "http//qudt.org/vocab/unit/SEC" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Siemens": "http//qudt.org/vocab/unit/S" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Sievert": "http//qudt.org/vocab/unit/SV" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Steradian": "http//qudt.org/vocab/unit/SR" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Tesla": "http//qudt.org/vocab/unit/T" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Volt": "http//qudt.org/vocab/unit/V" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Watt": "http//qudt.org/vocab/unit/W" ,
    "http://www.qudt.org/qudt/owl/1.0.0/unit/Instances.html#Weber": "http//qudt.org/vocab/unit/WB" ,
}
for k, v in replacements.items():
    data = data.replace(k, v)

open("../../resources/vocabularies/envthes.2.ttl", "w").write(data)
