import httpx

# https://plantnet.rbgsyd.nsw.gov.au/search/simple.htm
scientific_names = [
    "acaena echinata" ,
    "acanthiza reguloides" ,
    "acanthorhynchus tenuirostris" ,
    "acrocephalus australis" ,
    "ajuga australis" ,
    "alisterus scapularis" ,
    "amphibolurus muricatus" ,
    "anas" ,
    "anhinga novaehollandiae" ,
    "antechinus agilis" ,
    "anthochaera carunculata" ,
    "apis mellifera" ,
    "aprasia parapulchella" ,
    "araujia sericifera" ,
    "arthropodium milleflorum" ,
    "arum italicum" ,
    "asperula conferta" ,
    "asplenium flabellifolium" ,
    "austroaeschna pulchra" ,
    "austroargiolestes calcaris" ,
    "austrolestes annulosus" ,
    "austrostipa" ,
    "belenois java" ,
    "blechnum minus" ,
    "brachychiton populneus subsp populneus" ,
    "brachyscome rigidula" ,
    "brachyscome spathulata" ,
    "bursaria spinosa" ,
    "cacatua sanguinea" ,
    "caladenia" ,
    "callistemon pityoides" ,
    "calochilus campestris" ,
    "calotis anthemoides" ,
    "carex inversa" ,
    "casuarina cunninghamiana subsp cunninghamiana" ,
    "centranthus ruber" ,
    "centrolepis strigosa" ,
    "cercartetus nanus" ,
    "cheilanthes sieberi" ,
    "chelodina longicollis" ,
    "chenonetta jubata" ,
    "chenopodium album" ,
    "christinus marmoratus" ,
    "chrysocephalum apiculatum" ,
    "chrysodeixis argentifera" ,
    "cirsium vulgare" ,
    "clematis leptophylla" ,
    "climacteris picumnus victoriae" ,
    "columba livia" ,
    "conium maculatum" ,
    "cooraboorama canberrae" ,
    "coracina novaehollandiae" ,
    "corcorax melanorhamphos" ,
    "corunastylis clivicola" ,
    "corvus coronoides" ,
    "corybas hispidus" ,
    "cotoneaster glaucophyllus" ,
    "cracticus torquatus" ,
    "crinia" ,
    "ctenotus taeniolatus" ,
    "cygnus atratus" ,
    "cyperus sanguinolentus" ,
    "dacelo novaeguineae" ,
    "dama dama" ,
    "dampiera fusca" ,
    "daucus glochidiatus" ,
    "delma impar" ,
    "dichondra repens" ,
    "dimorphotheca ecklonis" ,
    "dipodium roseum" ,
    "diporiphora nobbi" ,
    "discaria pubescens" ,
    "diuris" ,
    "dodonaea viscosa" ,
    "drosera sp" ,
    "ectropis sp" ,
    "einadia nutans subsp nutans" ,
    "elanus axillaris" ,
    "eleocharis sphacelata" ,
    "eleusine tristachya" ,
    "eolophus roseicapilla" ,
    "erigeron sumatrensis" ,
    "eriochilus cucullatus" ,
    "eryngium ovinum" ,
    "euastacus sp" ,
    "eucalyptus" ,
    "eulamprus heatwolei" ,
    "falco berigora" ,
    "felis catus" ,
    "ficus carica" ,
    "gadopsis bispinosa" ,
    "gentianella polysperes" ,
    "glossodia major" ,
    "goodenia" ,
    "grevillea arenaria subsp arenaria" ,
    "hackelia suaveolens" ,
    "haliaeetus leucogaster" ,
    "halone sejuncta" ,
    "hemicordulia australiae" ,
    "hemiergis talbingoensis" ,
    "heteronympha paradelpha" ,
    "hydrocotyle sibthorpioides" ,
    "hydromys chrysogaster" ,
    "hylaeus honestus" ,
    "hypericum gramineum" ,
    "hypochaeris glabra" ,
    "isotoma fluviatilis subsp australis" ,
    "juncus sp" ,
    "junonia villida" ,
    "lampropholis sp" ,
    "lasioglossum peraustrale" ,
    "leptorhynchos squamatus subsp squamatus" ,
    "leucanthemum vulgare" ,
    "leucochrysum albicans subsp tricolor" ,
    "leucopogon fletcheri subsp brevisepalus" ,
    "leucopogon virgatus" ,
    "ligustrum sp" ,
    "lilaeopsis polyantha" ,
    "limnodynastes" ,
    "litoria" ,
    "lobelia" ,
    "lomandra filiformis subsp coriacea" ,
    "lotus australis" ,
    "lucia limbaria" ,
    "luzula densiflora" ,
    "lythrum hyssopifolia" ,
    "malacorhynchus membranaceus" ,
    "manorina melanocephala" ,
    "maratus vespertilio" ,
    "megachile lucidiventris" ,
    "megalyra sp" ,
    "melanodes anthracitaria" ,
    "microsorum pustulatum subsp pustulatum" ,
    "microtis sp" ,
    "mus musculus" ,
    "myiagra rubecula" ,
    "nassella" ,
    "notamacropus rufogriseus" ,
    "nyctemera amicus" ,
    "nycticorax caledonicus" ,
    "ocybadistes walkeri" ,
    "olearia" ,
    "orobanche minor" ,
    "oryctolagus cuniculus" ,
    "osphranter robustus" ,
    "oxalis thompsoniae" ,
    "oxylobium ellipticum" ,
    "oxyura australis" ,
    "papyrius nitidus" ,
    "paralucia aurifera" ,
    "pardalotus punctatus" ,
    "passer domesticus" ,
    "pelargonium australe" ,
    "pernattia pusilla" ,
    "petroica phoenicea" ,
    "pieris rapae" ,
    "pimelea linifolia" ,
    "pinus radiata" ,
    "platycercus eximius" ,
    "podargus strigoides" ,
    "pogona barbata" ,
    "polytelis swainsonii" ,
    "porphyrio melanotus" ,
    "prasophyllum" ,
    "psephotus haematonotus" ,
    "pseudonaja textilis" ,
    "pseudophryne pengilleyi" ,
    "pterostylis sp" ,
    "pyracantha sp" ,
    "pyrrholaemus sagittatus" ,
    "rattus rattus" ,
    "rhipidura" ,
    "rosa sp" ,
    "rytidosperma sp" ,
    "scleranthus diander" ,
    "senecio bathurstianus" ,
    "silene gallica var gallica" ,
    "solanum cinereum" ,
    "spatula rhynchotis" ,
    "stellaria pungens" ,
    "stictonetta naevosa" ,
    "strepera graculina" ,
    "sturnus vulgaris" ,
    "stylidium armeria subsp armeria" ,
    "swainsona" ,
    "synemon plana" ,
    "tachyglossus aculeatus" ,
    "tagetes erecta" ,
    "thelymitra sp" ,
    "thysanotus patersonii" ,
    "tiliqua" ,
    "trapezites eliena" ,
    "trapezites phigalia" ,
    "trichoglossus moluccanus" ,
    "trichosurus vulpecula" ,
    "triptilodiscus pygmaeus" ,
    "tympanocryptis lineata" ,
    "uperoleia laevigata" ,
    "utetheisa pulchelloides" ,
    "vanessa kershawi" ,
    "varanus rosenbergi" ,
    "veronica sp" ,
    "viburnum tinus" ,
    "vombatus ursinus" ,
    "wahlenbergia sp" ,
    "wallabia bicolor" ,
    "wurmbea dioica subsp dioica" ,
    "xerochrysum viscosum" ,
    "zizina otis" ,
]


for scientific_name in scientific_names:
    url = f"https://plantnet.rbgsyd.nsw.gov.au/cgi-bin/NSWfl.pl?page=nswfl&search=yes&namesearch={scientific_name.replace(' ', '+')}"
    r = httpx.get(url)
    if r.is_success:
        if not "No matches found. Check your spelling?" in r.text:
            html = r.text.split("<!-- ******************** end header file ********************  -->")[1]
            html = html.split("<br>")[1]
            html = html.split("</a>")[1]
            name = html.strip().strip(",").strip()

            print(f":{scientific_name.replace(" ", "-")} dct:vernacularName \"{name}\" .")
        else:
            print(f"{scientific_name} NOT")
