chebis = [
    "http://purl.obolibrary.org/obo/CHEBI:30050" ,
    "http://purl.obolibrary.org/obo/CHEBI_10545" ,
    "http://purl.obolibrary.org/obo/CHEBI_15377" ,
    "http://purl.obolibrary.org/obo/CHEBI_16130" ,
    "http://purl.obolibrary.org/obo/CHEBI_16526" ,
    "http://purl.obolibrary.org/obo/CHEBI_16646" ,
    "http://purl.obolibrary.org/obo/CHEBI_18059" ,
    "http://purl.obolibrary.org/obo/CHEBI_18230" ,
    "http://purl.obolibrary.org/obo/CHEBI_18248" ,
    "http://purl.obolibrary.org/obo/CHEBI_18291" ,
    "http://purl.obolibrary.org/obo/CHEBI_18422" ,
    "http://purl.obolibrary.org/obo/CHEBI_22984" ,
    "http://purl.obolibrary.org/obo/CHEBI_23044" ,
    "http://purl.obolibrary.org/obo/CHEBI_23116" ,
    "http://purl.obolibrary.org/obo/CHEBI_24127" ,
    "http://purl.obolibrary.org/obo/CHEBI_24527" ,
    "http://purl.obolibrary.org/obo/CHEBI_24866" ,
    "http://purl.obolibrary.org/obo/CHEBI_25107" ,
    "http://purl.obolibrary.org/obo/CHEBI_25491" ,
    "http://purl.obolibrary.org/obo/CHEBI_25555" ,
    "http://purl.obolibrary.org/obo/CHEBI_25944" ,
    "http://purl.obolibrary.org/obo/CHEBI_26195" ,
    "http://purl.obolibrary.org/obo/CHEBI_26216" ,
    "http://purl.obolibrary.org/obo/CHEBI_26708" ,
    "http://purl.obolibrary.org/obo/CHEBI_26833" ,
    "http://purl.obolibrary.org/obo/CHEBI_26848" ,
    "http://purl.obolibrary.org/obo/CHEBI_27027" ,
    "http://purl.obolibrary.org/obo/CHEBI_27325" ,
    "http://purl.obolibrary.org/obo/CHEBI_27363" ,
    "http://purl.obolibrary.org/obo/CHEBI_27560" ,
    "http://purl.obolibrary.org/obo/CHEBI_27568" ,
    "http://purl.obolibrary.org/obo/CHEBI_27573" ,
    "http://purl.obolibrary.org/obo/CHEBI_27594" ,
    "http://purl.obolibrary.org/obo/CHEBI_27638" ,
    "http://purl.obolibrary.org/obo/CHEBI_27888" ,
    "http://purl.obolibrary.org/obo/CHEBI_28017" ,
    "http://purl.obolibrary.org/obo/CHEBI_28073" ,
    "http://purl.obolibrary.org/obo/CHEBI_28112" ,
    "http://purl.obolibrary.org/obo/CHEBI_28659" ,
    "http://purl.obolibrary.org/obo/CHEBI_28685" ,
    "http://purl.obolibrary.org/obo/CHEBI_28694" ,
    "http://purl.obolibrary.org/obo/CHEBI_28966" ,
    "http://purl.obolibrary.org/obo/CHEBI_28984" ,
    "http://purl.obolibrary.org/obo/CHEBI_30778" ,
    "http://purl.obolibrary.org/obo/CHEBI_33233" ,
    "http://purl.obolibrary.org/obo/CHEBI_33284" ,
    "http://purl.obolibrary.org/obo/CHEBI_33292" ,
    "http://purl.obolibrary.org/obo/CHEBI_33815" ,
    "http://purl.obolibrary.org/obo/CHEBI_33853" ,
    "http://purl.obolibrary.org/obo/CHEBI_33937" ,
    "http://purl.obolibrary.org/obo/CHEBI_35255" ,
    "http://purl.obolibrary.org/obo/CHEBI_35381" ,
    "http://purl.obolibrary.org/obo/CHEBI_36005" ,
    "http://purl.obolibrary.org/obo/CHEBI_36080" ,
    "http://purl.obolibrary.org/obo/CHEBI_36233" ,
    "http://purl.obolibrary.org/obo/CHEBI_36928" ,
    "http://purl.obolibrary.org/obo/CHEBI_36934" ,
    "http://purl.obolibrary.org/obo/CHEBI_53276" ,
    "http://purl.obolibrary.org/obo/CHEBI_53725" ,
    "http://purl.obolibrary.org/obo/CHEBI_59163" ,
    "http://purl.obolibrary.org/obo/CHEBI_62967" ,
    "http://purl.obolibrary.org/obo/CHEBI_6457" ,
    "http://purl.obolibrary.org/obo/CHEBI_76413" ,
    "http://purl.obolibrary.org/obo/CHEBI_77853" ,
]

from rdflib import Graph

g = Graph().parse("chebi.owl", format="xml")

print(g.value)
